language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "pypy-5.3.1"
# command to install dependencies
install:
    - "pip install bitstring>=3.1.3"
    - "pip install pyflakes"
# command to run tests
script:
    - python setup.py test
    - pyflakes pybufrkit tests *.py
